export const routes = {
    home: "HomeScreen",
    wallet: "WalletScreen",
    login: "LoginScreen",
    register: "RegisterScreen",
    splash: "SplashScreen",
    code: "CodeScreen",
    welcome: "WelcomeScreen",
    drawer: "drawer",
    demand: "DemandScreen",
    recycle: "RecycleScreen",
    address: "AddressScreen",
    maps: "MapsScreen",
    dateTime: "DateTimeScreen",
    selectType: "SelectTypeScreen",
    profile: "ProfileScreen",
    support: "SupportScreen",
}